_target_: src.models.egnn.SingleGraphEGNN

n_layers: 8                    
m_dim: 16
dropout: 0.05
global_linear_dims: [256, 128, 64]
aggr: softmax
embedding_dims: [64, 32, 16, 16, 8, 8, 8, 8, 8, 8]
pooling: global_max
use_descs: true
use_embeddings: true