# GATv2 Model Configuration
_target_: src.models.gat.GATv2

in_channel: 9 # Number of node features 
hidden_channels: [ 64, 64, 64, 64, 64 ]
hidden_layers: [ 64 ]
heads: 4
edge_dim: null
dropout: 0.2
residual: true
use_descs: false
