_target_: src.models.polyBERT.PolyBERTForRegression

model_name: "kuelumbus/polybert"
num_labels: 5           # adjust to number of target properties
learning_rate: 5e-5
dropout: 0.0
freeze_encoder: true