# PyTorch Lightning Trainer Configuration
max_epochs: 50
# accelerator: gpu
accelerator: cpu
devices: auto
log_every_n_steps: 50

# enable_checkpointing: false

# Uncomment to enable early stopping
# callbacks:
#   - _target_: lightning.pytorch.callbacks.EarlyStopping
#     monitor: val_loss
#     mode: min
#     patience: 5
